name: playwright boilerplate

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.16.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Chrome browser dependency for Playwright
      run: npx playwright install

    - name: Run end-to-end tests
      run: npm run test:e2e

    - name:  Remove temporary files
      run: |
        echo "Cleaning up temporary files..."
        rm -rf ./node_modules  # Optionally remove node_modules
        echo "Cleanup completed."
