name: playwright boilerplate

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.16.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install browser dependencies
      run: npx playwright install

    - name: Run end-to-end tests
      run: npm run test:e2e

    - name: Generate Allure test report
      run: npm run test:report-generate

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./resources/test-results/allure-results/  # Path to Allure report folder
